<table>
  	<tr>
        <th>Brand</th>
        <th>Fuel level</th>
        <th>Tank volume</th>
        <th>Consumption</th>
        <th><?php echo (isset($data['filters']) ? 'Filters' : 'Plugs'); ?>
        </th>
  	</tr>
    <tr>  
        <td><?= htmlspecialchars($data['brand']); ?></td>
        <td><?= htmlspecialchars($data['fuel_level']); ?></td>
        <td><?= htmlspecialchars($data['tank_volume']); ?></td>
        <td><?= htmlspecialchars($data['consumption']); ?></td>
        <td><?= htmlspecialchars($data['filters'] ?? $data['plugs']); ?></td>
    </tr>
</table>
